### ISSUE TITLE
Thumbnails webp are not right in the einkauswelten article slider

### ISSUE THREAD

**Issue by DWEmbed** [FriendsOfShopware/FroshWebP#67]
Hello,

is that normal that the Thumbnails webp are not right in the einkauswelten article slider?

The pictures are display very small and the resolution are 2000x2000.

Best Regards

Daniel

**Comment by RicKro** [comment]
I have similar Issue.

In Mobile view port of Shopping World, the thumbnails are delivered in 1280 x 1280 (the biggest thumbnail we have generated in our Albums out of 3 sizes). 

With Webp disabled, the size of thumbnails is delivered correctly, but Insights is giving bad scores because of missing modern file format.

Shopware 5.6.6, Using PHP GD.

**Comment by shyim** [comment]
![image](https://user-images.githubusercontent.com/6224096/90983790-dc19d600-e570-11ea-8e02-5a8a0ba68b92.png)
I dont see any issues so far
